@base_url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmNlMTgyIiwic3ViIjozMywicm9sZXMiOlt7ImlkIjoxLCJuYW1lIjoiYWRtaW4ifSx7ImlkIjoyLCJuYW1lIjoiY2xpZW50ZSJ9XSwiaWF0IjoxNzE4NjI2OTgxLCJleHAiOjE3MTg2MjcwNDF9.X4VsOiF4GTRMnzKb4HqMar9oAJOABAUpTKaReOFE2IE




### Registro de usuario
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "username": "marce182",
  "email": "marce182@example.com",
  "password": "123456",
  "roles": [1, 2]
}

### Iniciar sesión de usuario
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "username": "marce182",
  "password": "123456"
}

### Obtener datos del usuario autenticado
GET {{base_url}}/auth/me
Authorization: Bearer {{token}}
